spring.application.name=kmo-digipres-be
spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.database=kmo-digipres-be
spring.data.mongodb.auto-index-creation=true
server.port=8080

kmosf.mail.smtp.host=${KMOSF_MAIL_SMTP_HOST:smtp.protonmail.ch}
kmosf.mail.smtp.port=${KMOSF_MAIL_SMTP_PORT:587}
kmosf.mail.smtp.username=${KMOSF_MAIL_SMTP_USERNAME:info@kmodigitalpresence.com}
kmosf.mail.smtp.password=${KMOSF_MAIL_SMTP_PASSWORD}
spring.webflux.base-path=/api
