spring.application.name=kmo-digipres-be
spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.database=kmo-digipres-be
spring.data.mongodb.auto-index-creation=true
server.port=8080
server.servlet.context-path=/api